apiVersion: v1
kind: Service
metadata:
  name: {{ include "demoapp.fullname" . }}
  labels:
    {{- include "demoapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports: {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "demoapp.selectorLabels" . | nindent 4 }}
